// Framer-style layout prop types
export type {
  PositionType,
  SizeType,
  LayoutType,
  DirectionType,
  DistributionType,
  AlignmentType,
  WrapType,
  FramerLayoutProps,
  UIComponentProps,
  ButtonProps,
  InputProps,
  CardProps,
  FrameProps,
  StackProps,
  GridProps,
  HeroProps,
  SidebarProps,
  FooterProps,
} from './framerProps';